

CREATE TABLE [dbo].[leavereport](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[empid] [varchar](15) NULL,
	[empname] [varchar](100) NULL,
	[company] [varchar](200) NULL,
	[designation] [varchar](100) NULL,
	[branch] [varchar](100) NULL,
	[empcategory] [varchar](100) NULL,
	[elavailed] [decimal](5, 1) NULL,
	[elentitlement] [decimal](5, 1) NULL,
	[elbalance] [decimal](5, 1) NULL,
	[excessdaysel] [decimal](5, 1) NULL,
	[elreason] [varchar](200) NULL,
	[scelavailed] [varchar](100) NULL,
	[scelentitlemant] [decimal](5, 1) NULL,
	[scelbalance] [decimal](5, 1) NULL,
	[excessdayscel] [decimal](5, 1) NULL,
	[scelreason] [varchar](200) NULL,
	[clavailed] [decimal](5, 1) NULL,
	[clentitlement] [decimal](5, 1) NULL,
	[clbalance] [decimal](5, 1) NULL,
	[excessdayscl] [decimal](5, 1) NULL,
	[clreason] [varchar](200) NULL,
	[slavailed] [decimal](5, 1) NULL,
	[slentitlement] [decimal](5, 1) NULL,
	[slbalance] [decimal](5, 1) NULL,
	[excessdayssl] [decimal](5, 1) NULL,
	[slreason] [varchar](200) NULL,
	[janel] [decimal](5, 1) NULL,
	[febel] [decimal](5, 1) NULL,
	[marchel] [decimal](5, 1) NULL,
	[aprel] [decimal](5, 1) NULL,
	[mayel] [decimal](5, 1) NULL,
	[junel] [decimal](5, 1) NULL,
	[julyel] [decimal](5, 1) NULL,
	[augel] [decimal](5, 1) NULL,
	[sepel] [decimal](5, 1) NULL,
	[octel] [decimal](5, 1) NULL,
	[novel] [decimal](5, 1) NULL,
	[decel] [decimal](5, 1) NULL,
	[janscel] [decimal](5, 1) NULL,
	[febscel] [decimal](5, 1) NULL,
	[marchscel] [decimal](5, 1) NULL,
	[aprscel] [decimal](5, 1) NULL,
	[mayscel] [decimal](5, 1) NULL,
	[junscel] [decimal](5, 1) NULL,
	[julyscel] [decimal](5, 1) NULL,
	[augscel] [decimal](5, 1) NULL,
	[sepscel] [decimal](5, 1) NULL,
	[octscel] [decimal](5, 1) NULL,
	[novscel] [decimal](5, 1) NULL,
	[decscel] [decimal](5, 1) NULL,
	[jansl] [decimal](5, 1) NULL,
	[febsl] [decimal](5, 1) NULL,
	[marchsl] [decimal](5, 1) NULL,
	[aprsl] [decimal](5, 1) NULL,
	[maysl] [decimal](5, 1) NULL,
	[junsl] [decimal](5, 1) NULL,
	[julysl] [decimal](5, 1) NULL,
	[augsl] [decimal](5, 1) NULL,
	[sepsl] [decimal](5, 1) NULL,
	[octsl] [decimal](5, 1) NULL,
	[novsl] [decimal](5, 1) NULL,
	[decsl] [decimal](5, 1) NULL,
	[jancl] [decimal](5, 1) NULL,
	[febcl] [decimal](5, 1) NULL,
	[marchcl] [decimal](5, 1) NULL,
	[aprcl] [decimal](5, 1) NULL,
	[maycl] [decimal](5, 1) NULL,
	[juncl] [decimal](5, 1) NULL,
	[julycl] [decimal](5, 1) NULL,
	[augcl] [decimal](5, 1) NULL,
	[sepcl] [decimal](5, 1) NULL,
	[octcl] [decimal](5, 1) NULL,
	[novcl] [decimal](5, 1) NULL,
	[deccl] [decimal](5, 1) NULL
) ON [PRIMARY]




