/****** Object:  Table [dbo].[EMPLOYEE_PERMISSIONS]    Script Date: 4/4/2016 2:45:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[EMPLOYEE_PERMISSIONS](
	[EMPLOYEE_CODE] [varchar](255) NOT NULL,
	[PERMISSIONS] [varchar](255) NULL,
 CONSTRAINT [PK_EMPLOYEE_PERMISSIONS] PRIMARY KEY CLUSTERED 
(
	[EMPLOYEE_CODE] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO